update upstream from Sail (#5)

diff --git a/bin/sail b/bin/sail
--- a/bin/sail
+++ b/bin/sail
@@ -158,9 +158,8 @@ function sail_is_not_running {
     exit 1
 }
 
-# Define podman Compose command prefix...
-podman compose &> /dev/null
-if [ $? == 0 ]; then
+# Define Podman Compose command prefix...
+if podman compose &> /dev/null; then
     DOCKER_COMPOSE=(podman compose)
 else
     DOCKER_COMPOSE=(podman-compose)
@@ -174,7 +173,7 @@ if [ -n "$SAIL_FILES" ]; then
         if [ -f "$FILE" ]; then
             DOCKER_COMPOSE+=(-f "$FILE")
         else
-            echo "${BOLD}Unable to find podman Compose file: '${FILE}'${NC}" >&2
+            echo "${BOLD}Unable to find Docker Compose file: '${FILE}'${NC}" >&2
 
             exit 1
         fi
@@ -425,7 +424,7 @@ elif [ "$1" == "pnpx" ]; then
         sail_is_not_running
     fi
 
-# Proxy YARN commands to the "yarn" binary on the application container...
+# Proxy Yarn commands to the "yarn" binary on the application container...
 elif [ "$1" == "yarn" ]; then
     shift 1
 
@@ -560,7 +559,14 @@ elif [ "$1" == "open" ]; then
     shift 1
 
     if [ "$EXEC" == "yes" ]; then
-        open $APP_URL
+
+        if [[ -n "$APP_PORT" && "$APP_PORT" != "80" ]]; then
+            FULL_URL="${APP_URL}:${APP_PORT}"
+        else
+            FULL_URL="$APP_URL"
+        fi
+
+        open "$FULL_URL"
 
         exit
     else
